version: '3'
services:

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  api:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017
    depends_on:
      - mongo

volumes:
  data: